name: security

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: false
          annotations: true
          min-severity: medium
          min-confidence: medium
          inputs: .github/workflows

  action-age-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Check GitHub Action ages
        uses: s4na/action-age-check@a441cca18c7f63dafa495465a91e554be83d8a3b
        with:
          min-age: 1w
          paths: .github/workflows
          fail-level: error
